## Practice

In [1]:
import numpy as np
from numpy import random

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [2]:
row_one = [1 for _ in range(10)]
inner_row = []
inner_row.extend([1])
inner_row.extend([0 for _ in range(8)])
inner_row.extend([1])
inner_row = [inner_row] * 8
matrix = [row_one]
matrix.extend(inner_row)
matrix.extend([row_one])
matrix = np.array(matrix)
print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


2. Create a 5*5 matrix with each row being 0 to 4

In [3]:
row = [i for i in range(5)]
matrix = [row] * 5
matrix = np.array(matrix)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [4]:
row_one = [0, 1] * 4
row_two = [1, 0] * 4
unit = [row_one] + [row_two]
matrix = unit * 4
matrix = np.array(matrix)
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [5]:
input_arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
mask = (input_arr % 2) == 1
output_arr = input_arr[mask]
print(output_arr)

[1 3 5 7 9]


5. Normalize a 5x5 random matrix 

In [6]:
matrix = random.random(size=(5, 5))
norm = np.linalg.norm(matrix, axis=1)
matrix_norm = matrix / norm
print(matrix_norm)

[[0.42716649 0.80938569 0.27579592 0.08243337 0.15832758]
 [0.26530972 0.14322353 0.16861761 0.88131273 0.41597045]
 [0.75858464 0.30529784 0.59391554 0.27888331 0.32155715]
 [0.51635492 0.57857387 0.37635888 0.26043939 0.16856993]
 [0.63437151 0.54464491 0.08031044 0.58151432 0.39209363]]


6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [7]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.70968871 0.90367228 1.29529888 1.04746804 0.36440947 0.85492248
 0.99249555 0.31908022 0.7069959  0.54411172]
[0.53380566 1.40884121 0.82483944 1.037466   1.37427122 1.1351712
 0.59628711 0.31268454 0.18044841 0.46025709]


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [8]:
n = 3
v = np.array([1, 2, 3, 4, 5], dtype=np.int64)
w = np.zeros(len(v) + (len(v) - 1) * n, dtype=np.int64)
w[::n + 1] = v
print(w)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))
First guess a result, then print the result, and finally find why

In [9]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in {np.nan})
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [10]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\OS\AppData\Local\Temp\ipykernel_11052\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\OS\AppData\Local\Temp\ipykernel_11052\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
